contact_links:
  - name: Are you looking for documentation on modelling-marti?
    url: https://mtwente.github.io/modelling-marti
    about: Please see the documentation for modelling-marti on its GitHub Pages page.
  - name: Do want to discuss modelling-marti with the community?
    url: https://github.com/mtwente/modelling-marti/discussions
    about: Please see the discussions page for modelling-marti.
blank_issues_enabled: true
