---
title: Modelling Marti
subtitle: Exposé
authors:
  - name: Moritz Twente
    affiliation: Universität Basel
    email: moritz.twente@unibas.ch
    orcid: 0009-0005-7187-9774
date: last-modified

bibliography: ../../assets/modelling-marti.bib
reference-section-title: Bibliografie
link-citations: true
lang: de
format:
#  pdf:
#    toc: true
#    number-sections: true
#    colorlinks: true
#    classoption: twocolumn
    #sansfont: "Jost-Light"
    #mainfont: "Jost-Light"
  html:
    comments:
      hypothesis: true
  #docx: default
  jats: default
---

Hans Marti (1913–1993) war ein Schweizer Architekt und Planer. Seine Arbeit in Bezug auf Orts-, Stadt- und Landesplanung machte ihn in der Schweiz zu „einem der wichtigsten Pioniere[]“ [@ruedinHansMartiPionier2008] im Bereich der institutionalisierten Raumplanung im heutigen Sinne. Als Marti sein Planungsbüro im Jahr 1948 gründet, steckt Planung als Disziplin (in der Schweiz) in den Kinderschuhen. Erst ab dem Zweiten Weltkrieg rücken in der Schweiz Städte als Objekt der Planung in den Blick [@hengstermannCountryProfileSwitzerland2022], bundesgesetzliche Grundlagen zur räumlichen Planung gibt es jedoch erst ab 1969 [@koll-schretzenmayrHansMartiUnd2008]. Während seiner Arbeit an Orts- und Regionalplanungen für u.a. Baden, Zofingen, Chur, Murten oder Faido betritt Marti daher immer wieder Neuland. Weiterhin war er Zürcher FDP-Gemeinderat (1958–1962) und anschliessend von 1962 bis 1967 Delegierter des Zürcher Stadtrates für Stadtplanung [@bockerMartiHans2007].

Im Rahmen dieser Seminararbeit rückt jedoch seine umfassende publizistische Tätigkeit in den Vordergrund, u.a. als Redaktor der Schweizerischen Bauzeitung (1949–1962). Etwa 190 Veröffentlichungen konnten über e-periodica.ch, e-newspaperarchives.ch sowie mittels einer Bibliografie [@ruedinHansMartiPionier2008] identifiziert werden. Unter der Annahme, dass sich Martis Pionierarbeit an der Herausbildung eines schweizerischen Berufsbildes Raumplaner*in insbesondere in der (fach-)öffentlichen Debatte sowie in Kommentaren in der Tagespresse nachvollziehen lässt, werde ich die einschlägigen Veröffentlichungen quantitativen Analysen unterziehen.

Die Ergebnisse dieser Seminararbeit dienen (idealerweise) als Vorarbeiten zu einem Panel an den Schweizerischen Geschichtstagen 2025 in Luzern, in dem ich mich mit anderen Aspekten von Hans Martis planerischer Arbeitsweise auseinandersetzen werde [@twenteHinterKonzeptUnd2025].

## Hypothesen/Fragestellungen

Zunächst stellt sich die Frage, welche Themen Marti im Rahmen seiner publizistischen Tätigkeit bearbeitet. Mit Blick auf die planerischen Fragestellungen der Zeit ist eine Hypothese, dass es vorrangig um Straßenausbau für den Autoverkehr sowie um Massenwohnungsbau geht. Da Marti selbst in Zürich wohnte und regelmässig in der NZZ publizierte, ist eine weitere Hypothese, dass Planungsvorhaben behandelt werden, die zu Martis aktiver Zeit speziell für die Stadt Zürich von Relevanz waren. Weiterhin vermute ich, dass auch die von seinem Büro bearbeiteten Planungen verstärkt Thema seiner Publikationen sind. Es stellt sich auch die Frage nach der Themenkonjunktur: Lassen sich im zeitlichen Verlauf von Martis Berufsleben – der älteste Artikel im Korpus datiert auf das Jahr 1946, der jüngste auf das Jahr 1989 – bestimmte Themen nur zu bestimmten Zeiten finden?

Eine zweite Perspektive auf den Textkorpus wird sich mit den beschriebenen bzw. erwähnten Orten befassen. Dazu rücken speziell die Toponyme in den Vordergrund, deren Erfassung eine explorative Herangehensweise an Martis geografischen Referenzrahmen erlauben. Als Arbeitshypothese gehe ich davon aus, dass auch hier der Kanton Zürich eine wichtige Rolle spielt. Weiterhin erwarte ich für Publikationen aus den 1950er Jahren eine Auseinandersetzung mit Basel als Reaktion auf die planungspolitischen Basler politischen Schriften von Lucius Burckhardt, Markus Kutter und Max Frisch [@burckhardtAchtungSchriften2016] – nicht nur aufgrund des generellen Presseechos, das Burckhardt et al. ausgelöst hatten, sondern auch, weil Marti etwa im Birrfeld [@eisingerStaedteBauenStaedtebau2004: 146] selbst mit vergleichbaren Planungsaufgaben konfrontiert war. Marti hat im Rahmen seiner Arbeit auch Auslandsreisen unternommen, u.a. nach Brasília, Paris und Norddeutschland. Es sind daher auch Berichte über und Referenzen über ausländische Bau-/Planungsprojekte zu erwarten. Meine Hypothese an dieser Stelle ist, dass sich – abgesehen von Zürcher und Deutschschweizer Projekten – im Korpus mehr Referenzen auf ausländische Städte finden werden als auf Orte in der Romandie.

## Korpus

Zurzeit erstelle ich einen Korpus, der von Hans Marti verfasste Artikel in Tageszeitungen und Fachzeitschriften umfasst. Die Recherche via e-periodica.ch hat in Kombination mit zusätzlichen Publikationen, die in einem Werkverzeichnis in einer Publikation über Martis Wirken aufgeführt sind [@ruedinHansMartiPionier2008] zu ca. 180 Artikeln[^1] geführt, davon etwa 60 Veröffentlichungen in der Neuen Zürcher Zeitung. Die restlichen Artikel wurden grossteils in Fachzeitschriften wie der Schweizerischen Bauzeitung oder der Zeitschrift Plan veröffentlicht. Vereinzelt sind auch Texte aus regionalhistorischen bzw. heimatkundlichen Publikationen, wie etwa den Badener Neujahrsblättern oder den Jurablättern Teil des Korpus. Drei Artikel sind auf Französisch verfasst.

[^1]: Die vollständige Bibliografie ist als [Zotero-Gruppe](https://www.zotero.org/groups/5722431/hansmarti-publications) verfügbar.

Alle Artikel sind als PDF über e-periodica.ch bzw. e-newspaperarchives.ch verfügbar. Die meisten Artikel habe ich mit der R-Package tabulapdf [@sepulvedaTabulapdfExtractTables2024] extrahiert. Für die Artikel aus der NZZ waren bereits Transkriptionen auf e-newspaperarchives.ch verfügbar, sodass ich diese direkt verwendet habe. Die NZZ-Artikel betreffend waren nur wenige geringfügige Korrekturen nötig, die ich direkt beim Kopieren der Texte aus dem Zeitungsarchiv per Hand vorgenommen habe. Für die mit tabulapdf extrahierten Zeitschriftenartikel von e-periodica.ch ist etwas mehr Data Cleaning notwendig, was ich in R hauptsächlich mit stringr [@wickhamStringrSimpleConsistent2023] und quanteda [@benoitQuantedaPackageQuantitative2018] vorgenommen habe.

Zum jetzigen Zeitpunkt habe ich zwei Korpora (die nach Abschluss der Aufräumarbeiten zu einem Gesamtkorpus zusammengefügt werden). Die Zeitungsartikel, die Hans Marti in der Neuen Zürcher Zeitung publiziert hat, ergeben als stemmed document-feature matrix ohne stopwords ca. 9‘900 features bzw. 567‘000 elements. Die übrigen Publikationen aus anderen Zeitschriften von e-periodica.ch umfassen als stemmed document-feature matrix ebenfalls ohne stopwords ca. 24‘000 features bzw. 313‘000 elements.

## Vorgehensweise

Den von mir mit quanteda erstellten Korpus werde ich vermutlich verschiedene Packages für unsupervised topic modelling verwenden, bisher habe ich probeweise seededlda [@watanabeSeededSequentialLDA2024] benutzt, um zu prüfen, ob der von mir zusammengestellte Korpus funktioniert. Weiterhin werde ich stm [@robertsStmPackageStructural2019] verwenden, um in einem iterativen Vorgehen eine passende Konfiguration/Anzahl an topics zu finden. Da sich die im Korpus enthaltenen Publikationen mit Blick auf das Publikum unterscheiden – insb. Tagespresse/NZZ vs. Fachpublikum/Bauzeitung,  werden hier mehrere Durchläufe nötig sein, um z.B. mit Korpus-Subsets ggfs. passendere topics zu finden.

Die Ergebnisse werden auf Grundlage der Ergebnisse der topic modelling-Versuche interpretiert und auf die von mir zu Beginn entwickelten Hypothesen zurückgespiegelt.