---
title: Planungsgeschichte
subtitle: Zum Institutionalisierungprozess der Schweizerischen Raumplanung 
authors:
  - name: Moritz Twente
    affiliation: Universität Basel
    email: moritz.twente@unibas.ch
    orcid: 0009-0005-7187-9774
date-modified: last-modified
bibliography: ../assets/modelling-marti.bib
reference-section-title: Bibliografie
link-citations: true
lang: de
format:
#  pdf:
#    toc: true
#    number-sections: true
#    colorlinks: true
#    classoption: twocolumn
    #sansfont: "Jost-Light"
    #mainfont: "Jost-Light"
    html: default
    #pdf: 
    #  documentclass: report
    #  classoption: twocolumn
    #  toc: true
  #docx: default
  #jats: default
editor: source
---

::: {.callout-note appearance="minimal"}
Dieser Inhalt wird laufend bearbeitet und dient als Vorschau auf die Inhalte eines längeren Textes zum Thema.
:::

Von seinen ersten planerischen Tätigkeiten in den letzten Jahren des Zweiten Weltkriegs bis zu seiner Pensionierung im Jahr 1979 [@koll-schretzenmayrHansMartiUnd2008] umspannt das Berufsleben von Hans Marti den Zeitraum, der für die Städte in der Schweiz morphologisch, architektonisch und sozioökonomisch prägend gewesen ist -- bezogen auf den Gebäudebestand 2011 sind über 40% aller Wohnungen in der Schweiz zwischen 1946 und 1980 gebaut worden [@althausSozialraumHochhausNachbarschaft2018, 99; vgl. @eisingerStaedteBauenStaedtebau2004, 10]. Im gleichen Zeitraum sind auch die entsprechenden planerischen Instrumente und Verfahren zum Umgang mit dem städtischen Raum politisch debattiert, konzipiert und umgesetzt worden.

### Planerische Themen im 20. Jahrhundert

Die Auffassung, welche Aufgabe(n) mit raumplanerischen Instrumenten angegangen werden sollen, verändert sich im Laufe des zwanzigsten Jahrhunderts entlang gesamtgesellschaftlicher Entwicklungen. Nach 1945 sind dabei neben der Entwicklung der Planungsgesetzgebung (s. Abschnitt [Enstehung und Institutionalisierung](#entstehung-und-institutionalisierung-von-planung-als-disziplin)) an sich fünf grundlegende Themenfelder[^polsystem] zentral, mit denen sich -- neben grundsätzlicher Debatten zur institutionellen Ausgestaltung und Gesetzgebung -- die ersten Planer*innen auseinandersetzen mussten.

[^polsystem]: Ich beziehe mich hier auf Aufgabenstellungen, die spezifisch für die räumliche Entwicklung der Schweiz ab ca. 1945 relevant wurden und Reaktionen innerhalb der institutionellen Landschaft der Schweiz erforderlich machten. Für eine übergeordnete theoretische Auseinandersetzung mit Raumplanung als Glied einer übergeordneten Gesellschaftspolitik, "as an expression, a result, and an instrument of the continuously changing economic, political, and social determinants of spatial development" [@grauInvestigatingUrbanPlanning2024, 1] siehe auch weitere Beiträge in dies. [-@grauHistoriesUrbanPlanning2024].

Erstens ist dies der die Etablierung der Planung für die grösseren Städte und Agglomerationen als Kernthema seit Mitte der 1980er Jahre. Nachdem der planerische Fokus zuvor hauptsächlich auf der Trennung von Landwirtschaftszonen vom Baugebiet und dem Schutz peripherer Regionen gelegen hatte [@hildebrandUrbaneSchweizUrbanistische2006, 73] und die gewünschte Ausgestaltung des Planungsobjekts 'Stadt' lange nicht konsensfähig umrissen war [@eisingerStaedteBauenStaedtebau2004, 311], stellt dies einen bedeutenden Paradigmenwechsel dar. Aus Planungsperspektive gelten die bisherigen "Störfaktoren" [Carl Fingerhuth in @koll-schretzenmayrGelungenMisslungenGeschichte2008, 151] Städte damit auf nationaler Ebene nicht mehr "in erster Linie [als] Gebilde, deren Ausufern zu verhüten" [@koll-schretzenmayrGelungenMisslungenGeschichte2008, 83] ist.

Aus dem Wachstum der Städte seit dem Zweiten Weltkrieg folgt zweitens, wie im restlichen Europa, die Motorisierung weiter Teile der Bevölkerung als wichtige Planungsaufgabe [@eisingerStaedteBauenStaedtebau2004, 10], womit im Zusammenhang mit den "zunehmend mächtigeren Imperative[n] der Verkehrsplanung" [@vonmoosErsteHilfeArchitekturdiskurs2021, 245] die Planung der autogerechten Stadt gemeint ist. Die Auswirkungen von Fernstrassenplanungen wurden auf nationaler Ebene und in den Gemeinden spürbar [vgl. @eisingerHansMartiUnd2008, 214f.] und führen "zu Qualitätseinbussen [...] im Wohnraum, im öffentlichen Raum und im Verkehrsraum" [@ritterRaeumeBewegungAutomobile2025, 228], wo Verkehr zum "heimliche[n] Raumplaner" [@bachtoldMehrMutEingriff2010, 26] wird.

In dieser Situation, in der mit Abrissen und tabula-rasa-Planungen das Auto in die bewohnte Stadt "eingepflegt" [@ritterRaeumeBewegungAutomobile2025, 227] werden soll, akzentuieren sich seit den 1950er-Jahren Fehlentwicklungen der Raumentwicklung [@ritterAchtungSchweizIdee2019, 13; @kochStadtebauSchweiz180019901992, 214], die später dafür sorgen werden, dass drittens Umwelt- bzw. Landschaftsschutz (wieder) zum planerischen Thema wird [@koll-schretzenmayrGelungenMisslungenGeschichte2008, 77f.; @vonmoosErsteHilfeArchitekturdiskurs2021, 222; @kochStadtebauSchweiz180019901992, 265]. Eine konsequente gesetzliche Verzahnung von Raumplanung und Umweltschutz wird trotz sich überschneidender Phasen der Institutionalisierung verpasst [@lendiGeschichteUndPerspektiven2018, 338; @wyrschVLPEspaceSuisse2018, 23], obwohl Raumplanung schon ab den 1950ern nicht zuletzt in Diskussionen über Gewässerschutz bzw. über den politischen Widerstand gegen Wasserkraftwerke als Thema in Erscheinung tritt [@bridelRaumplanung2011].

Das vierte Thema ist eine Folge dieser Entwicklungen: Die Entwicklung der Bodenpreise bzw. das Grundeigentum im Allgemeinen. Seit Mitte der 1950er-Jahre besteht ein Problembewusstsein für den Anstieg der Bodenpreise -- für eine Zürcher Seegemeinde etwa wird im Zeitraum 1945 bis 1962 eine Verzwanzigfachung der Preise errechnet [@eisingerHansMartiUnd2008, 208 Fussnote 5]. Die weiter zunehmende Verteuerung in den Städten und in der Agglomeration wird auf Spekulation zurückgeführt [@koll-schretzenmayrGelungenMisslungenGeschichte2008, 52]. Mit der im Jahr 1963 von SP und Gewerkschaften lancierten Bodenrechtsinitiative sollen Bund und Kantone ein Vorkaufsreicht bei Grundstücksverkäufen zwischen Privaten erhalten -- für die Gegenseite ein untragbarer Eingriff ins Privateigentum, durch den "die freiheitliche Wirtschafts- und Gesellschaftsordnung sozialistisch untergraben" werde [@grafSozialdemokratischesVorsprechenFindet2010, 296]. Die Bodenfrage, in den folgenden Jahrzehnten "immer wieder" [@kochStadtebauSchweiz180019901992, 263f.] thematisiert, kann als Beschleuniger im Institutionalisierungsprozess gesehen werden [@koll-schretzenmayrRuferWuste2010, 22].
 
Und fünftens schliesslich müssen die ersten Raumplaner (sic) ihre Disziplin als öffentliche Aufgabe in den 1960er-Jahren sogar gegenüber globalen Entwicklungen verorten: Unter dem Eindruck des Kalten Krieges bekommt die Raumplanung insofern auch eine militärische Komponente, als dass die Siedlungsstruktur als "wesentlicher Beitrag zur militärischen wie auch geistigen Landesverteidigung" [@koll-schretzenmayrGelungenMisslungenGeschichte2008, 73; s. auch @lendiGeschichteUndPerspektiven2018, 171f.] aufgefasst wird. Auf diese Weise verschafft die politische Lage den Instrumenten und Verfahren der Raumplanung eine politische Bühne, von der aus die Verankerung in der Bundesverfassung erst möglich wird. Auf der anderen Seite muss sich die noch junge Disziplin mit dem Misstrauen gegenüber dem Begriff *Planung* per se auseinandersetzen, liegt doch die Konnotation von Planung "mit Machtausübung des Staates und letztlich mit Kommunismus" [@herzogAchtungLandschaftLaesst2016, 57] rein terminologisch nahe und sorgt zu dieser Zeit[^anfang] für ein bis in die 1990er-Jahre verbreitetes Misstrauen [@lendiGeschichteUndPerspektiven2018, 352; @aregger10JahreLandesplanung1953, 225; @kochStadtebauSchweiz180019901992, 198; @gerosaAnfaengeStaedtebausUnd1983, 552][^misst], das aber nach @eisingerStaedteBauenStaedtebau2004 [132f.] und @hodgsonGebauteBeziehungenMax2023 [286] nicht als Aversion gegen Planung per se (über-)interpretiert werden sollte. Tatsächlichen Einfluss kommunistischer bzw. sozialistischer Positionen auf die Planungspraxis hat es ohnehin nicht gegeben [@lendiGeschichteUndPerspektiven2018, 170f.; @lendiPolitikBewegtRaumplanung2007, 76].

[^anfang]: Widerstand gegen vermeintliche Eingriffe in persönliche Freiheiten hat es freilich schon vor dem Kalten Krieg gegeben [vgl. @koll-schretzenmayrRuferWuste2010, 18].

[^misst]: Auch eine Annäherung an 'amerikanische' Verhältnisse wurde kritisch beäugt [vgl. @kochStadtebauSchweiz180019901992, 211].

### Entstehung und Institutionalisierung von Planung als Disziplin

Im folgenden Abschnitt werde ich skizzieren, wie in der Schweiz Raumplanung von ihren Anfängen in der Zwischenkriegszeit bis zur Annahme eines nationalen Raumplanungsgesetzes zum Ende der 1970er-Jahre zunächst im Kontext der Versorgungssicherheit thematisiert wird, nach 1945 wieder von der Agenda verschwindet und erst 1969 als Aufgabe staatlicher Institutionen in der Verfassung verankert wird.

#### Bis 1945

Als Initialzündung der Raumplanung im heutigen Sinne[^wurzeln] kann ein kurzes (verschriftlichtes) Referat des Architekten Armin @meiliAllgemeinesUberLandesplanung1933 betrachtet werden. Meili, der ein Ungleichgewicht von Land und wachsender Stadt diagnostiziert, ruft dazu auf, gesetzliche Grundlagen und eine Behörde zur systematischen Planung der landesweiten Raumentwicklung einzurichten. Verbunden mit einer Mahnung, die Schweiz sei im Vergleich mit anderen Staaten inhaltlich wie organisatorisch bereits im Hintertreffen, sieht er den grössten Handlungsbedarf in der Aufteilung der Landesfläche nach Nutzungszwecken (z.B. Landwirtschaft, Industrie, Siedlung, Verkehr). Ein Ziel ist, die fortschreitende Urbanisierung zulasten der ländlichen Räume zu begrenzen, aber zuvorderst steht für ihn -- mit Blick auf Auswirkungen der Weltwirtschaftskrise -- die Sicherung von Flächen zur Nahrungsmittelproduktion [@meiliAllgemeinesUberLandesplanung1933, 17, 20; vgl. @kochStadtebauSchweiz180019901992, 167, 183]. In der Zwischenkriegszeit spielt auch die Konservierung einer als ländliche Idylle imaginierten Schweiz eine Rolle -- Raumplanung als "kulturpolitische Bewegung einer Elite" [@schretzenmayrSchweizPlantDokumente2017, 11; vgl. @koll-schretzenmayrGelungenMisslungenGeschichte2008, 89]. Im fachlichen Umfeld von Meili erkennt @koll-schretzenmayrRuferWuste2010 [18] durchaus Sympathiebekundungen für dessen Ideen, doch die Reaktionen der Tagespresse -- und auch der Schweizerischen Bauzeitung! -- auf Meilis Vorschläge fallen negativ aus: Sie werden in seiner eigenen Wahrnehmung als zu bürokratisch, als unpassend für föderalistische Strukturen oder gleich als nicht relevant abgelehnt [@meili25JahreLandesplanung1958, 308].

[^wurzeln]: Eine Darstellung historischer Wurzeln der Schweizer Raumplanung avant la lettre bis zurück ins 19. Jahrhundert findet sich bei @lendiGeschichteUndPerspektiven2018 [117-122] sowie mit einem städebaulichen Fokus bei @kochStadtebauSchweiz180019901992 [z.B. 172f.].

Im Zweiten Weltkrieg aber haben planerische Themen wieder Konjunktur -- in Bezug auf die Arbeitsbeschaffungsmassnahmen [@koll-schretzenmayrGelungenMisslungenGeschichte2008, 21] und (hauptsächlich) zur Sicherstellung der Landesversorgung unter den Bedingungen der Kriegswirtschaft [@hengstermannCountryProfileSwitzerland2022]. Doch die ersten Planer (sic) fassen ihr Aufgabengebiet viel weiter, sehen sich selbst in "eine[r] der Schlüsselpositionen zur Lösung wirtschaftlicher, kultureller, sozialer und politischer Probleme der nächsten hundert Jahre schweizerischen Schicksals" [@meiliZeitschriftPlanWird1944, 26]. Kurzfristig entsteht der Eindruck, die Schweiz sei ein "Laboratorium fortschrittlicher Planung" [@vonmoosErsteHilfeArchitekturdiskurs2021, 203]. Doch diese staatliche Planung, deren grundlegende Aufgabe die Erhaltung von landwirtschaftlicher Nutzfläche bleibt, hat wenig mit einer langfristigen Koordination raumwirksamer Tätigkeiten zu tun [@koll-schretzenmayrGelungenMisslungenGeschichte2008, 21f.]. Abgesehen von der Gründung der Schweizerischen Vereinigung für Landesplanung im Jahr 1943 [@hildebrandUrbaneSchweizUrbanistische2006, 71] hat es keine nachhaltig wirksamen institutionellen Impulse für die Nachkriegszeit gegeben [@kochStadtebauSchweiz180019901992, 167] und es bleibt auf nationaler Ebene bei einer für Meili rückblickend "unvorstellbaren Planlosigkeit" [-@meili25JahreLandesplanung1958, 308].

#### Nach 1945

Dass planerische Anliegen nach 1945 wieder in eine Position wie noch vor dem Zweiten Weltkrieg zurückgeworfen werden, liegt nicht zuletzt an der Themenkonjunktur. Priorisiert wird nun, die Verkehrsnetze auf die wachsende Bedeutung des motorisierten Individualverkehrs vorzubereiten [vgl. @gisler-jauchAutomobil2015]. Diese neue Aufgabe, kombiniert mit von Gemeinden und aus Wirtschaftskreisen geäusserten Vorbehalten, sorgt dafür, dass grundsätzliche Diskussionen über Raumplanung kaum mehr reüssieren. Eine Ausnahme scheint das Tessin darzustellen, für das @gerosaAnfaengeStaedtebausUnd1983 [552] in der unmittelbaren Nachkriegszeit ein erstarkendes Interesse für raumplanerische Vorhaben beschreibt. In den in Fachkreisen stattfindenden Diskussionen in der Deutschschweiz kann sich die Idee von Planung als landesweiter Aufgabe jedoch nicht durchsetzen, unter anderem in den Rechtswissenschaften. Dort spielt insbesondere das Verhältnis von staatlicher Planung zum individuellen Eigentum eine Rolle -- ein Konflikt, der sich schon in den 1930er-Jahren herauskristallisiert hatte [@meili25JahreLandesplanung1958, 308; @meiliVergeudungSchweizerErde1964, 29]. Der Schweizerische Juristentag setzte sich an mehreren Jahrestagungen mit diesem Thema auseinander und sprach sich etwa 1947 dafür aus, dass das Eigentum höher zu gewichten sei als übergreifende planerische Interessen [@vonmoosErsteHilfeArchitekturdiskurs2021, 244f.]. Die Delegation der Vereinigung für Landesplanung verliess die Tagung "verprügelt, beschimpft und verlacht" [@marti25JahreLandesplanung1968a, 743].

In der Folge fand bis ca. 1960 keine politische Debatte über Raumplanung mehr statt, "Wachstum schien ganz einfach keine Probleme zu verursachen" [@koll-schretzenmayrGelungenMisslungenGeschichte2008, 89], die planerisch gelöst werden müssten. Lediglich in den Bereichen Landschaftsschutz, Heimatschutz und Tiefbau etablierten sich bereits planerische Prozesse, die aber zuvorderst als architektonische Angelegenheiten angesehen wurden [@vonmoosErsteHilfeArchitekturdiskurs2021, 215–217; @eisingerStaedteBauenStaedtebau2004, 303f.]. Als wissenschaftliche Disziplin findet Planung dagegen Gehör an akademischen Institutionen, z.B. in Form eines bereits 1943 gegründeten Instituts im Fachbereich Geografie der ETH Zürich [@koll-schretzenmayrGelungenMisslungenGeschichte2008, 23]. Eigens konzipierte Lehrveranstaltungen zu raumplanerischen Themen werden auch für inhaltlich verwandte Studiengänge angeboten, neben der ETH auch an der Fachhochschule in Rapperswil sowie zeitweise in Windisch [@lendiGeschichteUndPerspektiven2018, 229f.].

#### Ab 1960

Die politische Debatte nimmt neue Fahrt auf, als ab den 1960er-Jahren Themen wie Wohnungsnot, Zersiedelung und Naturschutz erhöhte Aufmerksamkeit bekommen [@koll-schretzenmayrRuferWuste2010]. Neben den Folgen des rasanten Bevölkerungs- und Wirtschaftswachstums beschleunigen im Kontext des Kalten Krieges weiterhin die Furcht vor Enteignung und erneut der Themenkomplex Landesverteidigung/Bevölkerungsschutz die "'heimliche' Institutionalisierung" [@hasenohrlKollSchretzenmayrMartina20082010, 332] der Raumplanung. Damit verschiebt sich auch das Verhältnis von Planung und Wirtschaft, das nicht mehr als Antagonismus aufgefasst wird. Planung wird nun vielmehr als dem Wirtschaftswachstum förderliche Tätigkeit verstanden, mit der die bestehende Gesellschaftsordnung stabilisiert werden kann [@koll-schretzenmayrGelungenMisslungenGeschichte2008, 332]. Raumplanung wird "politikreif" [@lendiZurGeschichteSchweizerischen2006a, 71].

Bevor Raumplanung offiziell als öffentliche Aufgabe im Jahr 1969 in die Bundesverfassung aufgenommen wird, hatte jedoch noch eine längere politische Auseinandersetzung um den Umgang mit privatem Bodenbesitz stattgefunden. Diese konnte gelöst werden, indem gleichzeitig Formulierungen zur Eigentumsgarantie Eingang in die Verfassung fanden [@hengstermannCountryProfileSwitzerland2022; @schretzenmayrSchweizPlantDokumente2017, 73] -- ein "historischer Kompromiss" [@knoepfelTransformationRolleStaates2012, 420]. Zur Umsetzung der neuen Staatsaufgabe müssen in der Folge nationale und kantonale Planungsgesetze erarbeitet werden [vgl. @kochStadtebauSchweiz180019901992, 263f.]. Ein erster Entwurf für ein Raumplanungsgesetz auf Bundesebene wird im Jahr 1976 in der Volksabstimmung abgelehnt, tritt aber in dann abgeschwächter Form zum Jahresbeginn 1980 in Kraft[^aktuell]. Als die zentralen Ansätze dieser Gesetzgebung sind "die Trennung von Siedlungs- und Nicht-Siedlungsgebiet, mit den besonderen Zielen der kontrollierten Entwicklung des Baugebietes, der Sicherung des Nicht-Siedlungsgebietes zugunsten der Landwirtschaft (Einführung der Landwirtschaftszone), von Schutzanliegen (Schutzzonen) sowie [die] Trennung des Bauland- vom landwirtschaftlichen Bodenmarkt" [@lendiZurGeschichteSchweizerischen2006a, 71] zu nennen. Erst durch das Raumplanungsgesetz wird Raumplanung auch flächendeckend ausserhalb der grösseren Städte zum Thema [@althausSozialraumHochhausNachbarschaft2018, 106].

[^aktuell]: Zu einer Revision des Raumplanungsgesetzes kam es erstmals im Jahr 2014 [@hengstermannCountryProfileSwitzerland2022; @lezziStadtUndRaumentwicklung2018, 2329f.].

<!-- * Kürzestzusammenfassung System heute? Ebenen, Ämter, Pläne? Verweis @hengstermannCountryProfileSwitzerland2022, https://www.espacesuisse.ch/sites/default/files/documents/2021-3-17-SNP-BBew-Pzip.pdf Slide 5, https://www.curem.uzh.ch/static/events/archive/2021-08-16/pdfs/02_Forum%20Raumwissenschaften_2021_Referat_B%C3%BChlmann.pdf Slide 21, tragende Funktion der Kantone @lendiGeschichteUndPerspektiven2018, 202 -->

#### Rückblickende Beurteilungen

Bereits 1964 war für Armin Meili die Zeit verstrichen, in der durch umfassende planerische Weichenstellungen noch wirksam Einfluss auf die räumliche Entwicklung genommen werden konnte [@vonmoosErsteHilfeArchitekturdiskurs2021, 240] und knapp zwanzig Jahre später ist Martin Lendi der Auffassung, der "Versuch, eine nationale Raumplanung konzeptionell zu entwerfen, [sei] aufgegeben worden" [-@lendiStadtplanungAlsPolitische1983, 6]. Beurteilungen über die Wirksamkeit der in der Schweiz dennoch zur Verfügung stehenden raumplanerischen Verfahren und Instrumente konnten zu diesem Zeitpunkt -- für Lendi [-@lendiZurGeschichteSchweizerischen2006a, 80] befand sich die Schweiz auch im Jahr 1990 noch in der Pionierphase der Planung -- freilich noch nicht vorgenommen werden. Aber auch jüngere Einschätzungen[^wandel] zur Ausgestaltung der planerischen Instrumente und Verfahren durch relevante Akteur\*innen fallen gemischt aus [@lezziStadtUndRaumentwicklung2018, 2327; @kisslingLangerWegMit2023; @lendiGeschichteUndPerspektiven2018, 331-350; @bachtoldMehrMutEingriff2010; @kundigMehrDimensionenRaumplanung2010; @herbstWirSelberBauen2018, 97; @nahrathEffetsMisePlace2002; vgl. @koll-schretzenmayrGelungenMisslungenGeschichte2008; -@koll-schretzenmayrRuferWuste2010].

[^wandel]: Eine direkte Verbindung zwischen Meilis Kritik aus den 1960er-Jahren und zeitgenössischen Beurteilungen ist jedoch nur bedingt möglich, hat sich doch das Verständnis, was Planung mit welchen Methoden leisten kann und soll, im 20. Jahrhundert stark verändert, vgl. @fuerstPlanung2018 und für die Schweiz @wyrschVLPEspaceSuisse2018 [27].

Das System der schweizerischen Raumplanung wird von verschiedenen Akteur\*innen aufgrund der Langsamkeit kritisiert, mit der sich die politischen Prozesse vollziehen -- ob aufgrund direktdemokratischer Elemente [Jacques Herzog in @herzogAchtungLandschaftLaesst2016, 35] oder eines generellen "helvetisch ängstliche[n] und oft auch politisch argumentierende[n] Beharrungsvermögen[s]" [@schlappnerTodeArchitektHans1993]. Das breit rezipierte 'Städtebauliche Porträt' des ETH Studio Basel beschreibt Urbanität in der Schweiz als von "einer Art Kultur des Verweigerns und Verhinderns" [@dienerSchweizStaedtebaulichesPortraet2006, 17] geprägt. Auch Hans Marti hat die unmittelbare Erfahrung gemacht, "scheitern sehen zu müssen, was er an Gutem vorgeschlagen hatte" [@schlappnerTodeArchitektHans1993; vgl. @maissenHochhausUndTraktor2014, 42; @steinerDochRuferWuste1987]. Generell gilt, dass von den planerischen Ideen und Konzepten der zweiten Hälfte des 20. Jahrhunderts in der Schweiz vieles nur in Ansätzen realisiert werden konnte. So spielten sich grosse Ideen wie die Neue Stadt "vorwiegend auf Zeichenpapier, in Fachliteratur und zwischen Buchdeckeln ab" [@eisingerStaedteBauenStaedtebau2004, 146].